<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xml.xsl"?>
<metadata>
	<IdInfo>
		<datId>${datId!}</datId>
		<resTitle>${resTitle!}</resTitle>
		<engTitle>${engTitle!}</engTitle>
		<language>${language!}</language>
		<keyword>${keyword!}</keyword>
		<keywordEng>${keywordEng!}</keywordEng>
		<uptDate>${uptDate!}</uptDate>
		<pubDate>${pubDate!}</pubDate>
		<lastAlterDate>${lastAlterDate!}</lastAlterDate>
	</IdInfo>
	
	
	<ContInfo>
		<abstract>${abstract1!}</abstract>
		<abstract1Eng>${abstract1Eng!}</abstract1Eng>
		<tpCat>
			<cateName>${cateName!}</cateName>
			<cateCode>${cateCode!}</cateCode>
			<cateStd>${cateStd!}</cateStd>
		</tpCat>
		<spatialCov>
			<planeCov>
				<coordCov>
					<lftBtmCoord>${lftBtmCoord!}</lftBtmCoord>
					<rightTopCoord>${rightTopCoord!}</rightTopCoord>
				</coordCov>
				<coordPoint>${coordPoint!}</coordPoint>
				<corSys>${corSys!}</corSys>
				<proSys>${proSys!}</proSys>
				<spaRes><equScale>${equScale!}</equScale></spaRes>
				<gridSize>${gridSize!}</gridSize>
				<posDes>${posDes!}</posDes>
			</planeCov>
			<verCov>
				<altCov>
					<topVer>${topVer!}</topVer>
					<lowVer>${lowVer!}</lowVer>
				</altCov>
				<altPoint>${altPoint!}</altPoint>
				<altDesc>${altDesc!}</altDesc>
				<atiSys>${atiSys!}</atiSys>
				<atiInterval>${atiInterval!}</atiInterval>
			</verCov>
		</spatialCov>
		<timeCov>
			<timePeriod>
				<begDate>${begDate!}</begDate>
				<endDate>${endDate!}</endDate>
			</timePeriod>
			<timePoint>${timePoint!}</timePoint>
			<timeInterval>${timeInterval!}</timeInterval>
		</timeCov>
		<dataQuant>${dataQuant!}</dataQuant>
		
	</ContInfo>
	
	
	<SrcInfo>
		<srcType>${srcType!}</srcType>
		<site>
			<siteID>${siteID!}</siteID>
			<siteName>${siteName!}</siteName>
			<siteCoordinate>${siteCoordinate!}</siteCoordinate>
			<sitePosDesc>${sitePosDesc!}</sitePosDesc>
			<siteContact>${siteContact!}</siteContact>
		</site>
		<instrument>
			<instID>${instID!}</instID>
			<instName>${instName!}</instName>
			<instCat>${instCat!}</instCat>
			<instSpec>${instSpec!}</instSpec>
			<instContact>${instContact!}</instContact>
		</instrument>
		<prcMethod>
			<methodName>${methodName!}</methodName>
			<methodDesc>${methodDesc!}</methodDesc>
			<originalSrc>
				<originalDesc>${originalDesc!}</originalDesc>
				<originalContact>${originalContact!}</originalContact>
			</originalSrc>
		</prcMethod>
		<qaDesc>${qaDesc!}</qaDesc>
		<prdContact>${prdContact!}</prdContact>
	</SrcInfo>
	
	<DissInfo>
		<dataStorage>
			<dataType>${dataType!}</dataType>
			<dataFormat>${dataFormat!}</dataFormat>
			<formatVersion>${formatVersion!}</formatVersion>
		</dataStorage>
		<serviceInfo>
			<serviceType>${serviceType!}</serviceType>
			<serviceLink>${serviceLink!}</serviceLink>
			<serviceParas>
				<paraName>${paraName!}</paraName>
				<paraValue>${paraValue!}</paraValue>
			</serviceParas>
			<accessClass>${accessClass!}</accessClass>
		</serviceInfo>
		<useDesc>${useDesc!}</useDesc>
		<copyRight>
			<copyRightDesc>${copyRightDesc!}</copyRightDesc>
			<citation>${citation!}</citation>
		</copyRight>
		<dissContact>${dissContact!}</dissContact>
	</DissInfo>
	
	<MdDesp>
		<mdId>${mdId!}</mdId>
		<MdContact>${mdContact!}</MdContact>
		<mdDateUpd>${mdDateUpd!}</mdDateUpd>
	</MdDesp>
	
	<PointCoordType>
		<pointLong>${pointLong!}</pointLong>
		<pointLat>${pointLat!}</pointLat>
	</PointCoordType>
	<respParty>
		<orgName>${orgName!}</orgName>
		<phone>${phone!}</phone>
		<address>${address!}</address>
		<postcode>${postcode!}</postcode>
		<email>${email!}</email>
	</respParty>
	
	
</metadata>